### ISSUE TITLE
Please consider using library for GSM module

### ISSUE THREAD

**Issue by toomasz** [CircuitMess/CircuitMess-Ringo#12]
Hi, i noticed you are using bare at commands for interacting with modem. Just letting you know that you can use my library designed for simcom modems: https://github.com/toomasz/SimcomGsmLib
It's designed to work on ESP32 and is probably the most stable one as it doesn't use any aduino strings and has proper error handling implemented.

**Comment by MiLeG** [comment]
Hey,
Thanks for the tip. The library seems really useful and could potentially simplify the code a bunch, but we've got our hands full at the moment with all sorts of important things.
We'll keep the issue open and see what we can do in a week or so.
