### ISSUE TITLE
Unit won't turn on after charging

### ISSUE THREAD

**Issue by jeffbellamy** [CircuitMess/CircuitMess-Ringo#42]
Unit won't turn on after charging. Screen remains blank. I can see a red light in the interior but that is all.

**Comment by robbie8-bit** [comment]
Hi Jeff,

For these kind of issues please send an email to contact@circuitmess.com. 
GitHub repo is a place where only detailed software issues are being resolved. 

Can you please also add a bit more to the mail? Maybe  take a couple of photos of the soldering pads, the screen and the phone in general.

Thanks,
Robert

**Comment by wbphelps** [comment]
Hi, 
I'm not Jeff 
Will 

(Sent by an alien from the Andromeda Galaxy - read at your own risk!)
