### ISSUE TITLE
images in README.md broken

### ISSUE THREAD

**Issue by Patronics** [CircuitMess/CircuitMess-Ringo#46]
None of the images embedded in the readme file seem to exist, and the sources they link to, such as [this one](https://camo.githubusercontent.com/94143efb32163c64778b26fb1844586b5fe710da/68747470733a2f2f7777772e636972637569746d6573732e636f6d2f77702d636f6e74656e742f75706c6f6164732f44534330353434335f31303234783638332d312e6a7067) just say "Not Found"

**Comment by robbie8-bit** [comment]
Thanks for the issue - it has been resolved and everything is working now. :)

Cheers,
Robert
